//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashupApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hashtag
    {
        public Hashtag()
        {
            this.Instagram = new HashSet<Instagram>();
            this.Tweet = new HashSet<Tweet>();
            this.Trend = new HashSet<Trend>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Instagram> Instagram { get; set; }
        public virtual ICollection<Tweet> Tweet { get; set; }
        public virtual ICollection<Trend> Trend { get; set; }
    }
}
