//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashupApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trend
    {
        public int Id { get; set; }
        public int HashtagId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ExpiresAt { get; set; }
    
        public virtual Hashtag Hashtag { get; set; }
    }
}
